
import Heading from './components/heading/heading'
import './globals.css'
import { Inter } from 'next/font/google'
import { Inconsolata as Mono, DM_Sans as Sans, Roboto_Slab as Serif} from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const serif = Serif({ subsets: ['latin'], variable: '--font-serif'})
const mono = Mono({subsets: ['latin'], variable: '--font-mono'})
const sans = Sans({subsets: ['latin'], weight: '400', variable: '--font-sans'})


export const metadata = {
  title: 'Tom Boberek • Portfolio Website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Heading className='sticky top-0 z-50'/>
        {children}
      </body>
    </html>
  )
}
