name: Test Astro Site

on:
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build project
        run: npm run build
      
      - name: Start Astro preview server
        run: npm run preview &
        env:
          NODE_ENV: production

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:4321

      - name: Run Cypress tests with coverage
        uses: cypress-io/github-action@v6
        with:
          start: false
          wait-on: http://localhost:4321
          wait-on-timeout: 60 # seconds
          command: npm run cy:coverage # or your custom script for coverage
        env:
          NODE_ENV: production
          
      - name: Report coverage
        run: |
          npx nyc report --reporter=text-summary
          npx nyc check-coverage --lines 80 --functions 80 --branches 80 --statements 80

      - name: Run Lighthouse CI
        run: lhci autorun --collect.url=http://localhost:4321
